package com.example.notes;

import java.io.Serializable;
import java.util.Date;

import androidx.room.ColumnInfo;
import androidx.room.Entity;
import androidx.room.ForeignKey;
import androidx.room.PrimaryKey;

import static androidx.room.ForeignKey.CASCADE;

/**
 * Reminder stores all the reminders the user adds.
 * Reminder contains an autogenerated ID, the note ID reference, the date of the reminder, and
 * the frequency of the reminder.
 *
 * Foreign Key constraint is that the NoteID set must be an ID from the Note table.
 *
 * |ID|NoteID|DateTime|Frequency|
 */

@Entity(foreignKeys = @ForeignKey(entity = Note.class,
parentColumns = "ID",
childColumns = "NoteID",
onDelete = CASCADE,
onUpdate = CASCADE))
public class Reminder implements Serializable {
    @PrimaryKey(autoGenerate = true)
    @ColumnInfo(name = "ID")
    private long mID;
    @ColumnInfo(name = "NoteID")
    private long mNoteID;
    @ColumnInfo(name = "DateTime")
    private Date mDateTime;
    @ColumnInfo(name = "Frequency")
    private ReminderFrequency mFrequency;

    public Reminder(long noteID, Date dateTime, ReminderFrequency frequency){
        this.mNoteID = noteID;
        this.mDateTime = dateTime;
        this.mFrequency = frequency;
    }

    // Getters
    public Date getDateTime(){
        return this.mDateTime;
    }
    public long getID(){
        return this.mID;
    }
    public long getNoteID(){
        return this.mNoteID;
    }
    public ReminderFrequency getFrequency(){
        return this.mFrequency;
    }

    // Setters
    public void setID (long id){
        this.mID = id;
    }
    public void setDateTime(Date date){
        this.mDateTime = date;
    }
    public void setNoteID(long noteID){
        this.mNoteID = noteID;
    }
    public void setFrequency(ReminderFrequency frequency){
        this.mFrequency = frequency;
    }

}

